---
- name: ensure nginx is installed
  apt: pkg=nginx state=latest

- name: copy the nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: copy the nginx default vhost configuration
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default
  notify:
    - restart nginx

- name: copy the nginx default vhost configuration
  template: src=default.j2 dest=/etc/nginx/sites-enabled/default
  notify:
    - restart nginx

- name: copy the nginx default index.html
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
  notify:
    - restart nginx

- name: copy the nginx default 500 error page
  template: src=50x.html.j2 dest=/usr/share/nginx/html/50x.html
  notify:
    - restart nginx

- name: copy fast cgi params
  template: src=fastcgi_params.j2 dest=/etc/nginx/fastcgi_params
  notify:
    - restart nginx