# Nginx playbook
---
- hosts: webserver-nginx
  remote_user: "{{ remote_user }}"
  tasks:
      - name: ensure nginx is installed
        apt: pkg=nginx state=present

      - name: install php5-fpm
        apt: pkg=php5-fpm state=present

      - name: copy the nginx vhost file
        template: src=config/nginx.j2 dest=/etc/nginx/sites-available/neos-workshop.box

      - name: enable the nginx vhost file
        file: src=/etc/nginx/sites-available/neos-workshop.box dest=/etc/nginx/sites-enabled/neos-workshop.box state=link

      - name: restart services
        service: "name={{ item }} state=restarted"
        with_items:
            - nginx