
---
- name: add dotdeb key
  apt_key: url={{ dotdeb_key }} state=present
  when: php_version == '5.5'
  tags: [php]

- name: add dotdeb repository
  apt_repository: repo='{{ dotdeb_repository_php55 }}' state=present update_cache=yes
  when: php_version == '5.5'
  tags: [php]

- name: install PHP5 packages
  apt: pkg={{ item }} state=present
  with_items:
    - php5-cli
    - php5-dev
    - php5-curl
    - php5-fpm
    - php5-gd
    - php5-imagick
    - php5-intl
    - php5-mysql
    - php5-memcache
    - php5-redis
    - php5-mcrypt
  tags: [php]

- name: disable nginx vhost
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  notify:
    - restart php-fpm
  tags: [php]

- name: php fpm global configuration
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/php-fpm.conf
  notify:
    - restart php-fpm
  tags: [fpm, php]

- name: php ttree configuration
  template: src=99-ttree.conf.j2 dest=/etc/php5/conf.d/99-ttree.conf
  notify:
    - restart php-fpm
  tags: [fpm, php]

- name: php fpm log permissions
  file: "path=/var/log/php5-fpm.log owner=root group=adm mode=0644 state=file"
  tags: [fpm, php]

- name: install PHP 5.4 APC packages
  apt: pkg=php5-apc state=present
  when: php_version != '5.5'
  notify:
    - restart php-fpm
  tags: [php]

- name: install composer globally
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: [composer, php]

- name: set composer permissions
  file: "path=/usr/local/bin/composer owner=root group=root mode=0755 state=file"
  tags: [composer, php]