---
- hosts: all
  roles:
     - common

- hosts: dbserver
  vars:
    mysql_dbs:
    - name: playground

    mysql_users:
    - name: playground
      pass: playground
      priv: "playground.*:ALL"

  roles:
     - role: mysql-client
       mysql_pkgs:
         - mysql-client-5.6

     - role: mysql-server
       mysql_pkgs:
         - python-selinux
         - mysql-server-5.6
         - python-mysqldb
       mysql_root_db_pass: root
       mysql_db: "{{ mysql_dbs }}"
       mysql_users: "{{ mysql_users }}"

- hosts: webserver
  vars:
    vhosts:
      - name: neos-workshop.box
        enabled: Yes
        php: No
        server_name: neos-workshop.box
        type: redirect-domain
        destination_domain: www.neos-workshop.box

      - name: www.neos-workshop.box
        enabled: Yes
        php: Yes
        server_name: www.neos-workshop.box
        type: typo3-neos
        app_user: vagrant
        app_group: vagrant
        deploy:
          composer: Yes
          git: git://git.typo3.org/Neos/Distributions/Base.git
          version: HEAD

      - name: www.dummy.box
        enabled: Yes
        php: Yes
        server_name: www.dummy.box
        type: typo3-neos
        app_user: vagrant
        app_group: vagrant

  roles:
    - role: memcached

    - role: webserver-nginx
      user: vagrant

    - role: webserver-php

    - role: php-pecl
      php_pecl_extensions:
       - yaml

    - role: webserver-vhosts
      vhosts: "{{ vhosts }}"


